### ISSUE TITLE
permettre de lister les cours par type

### ISSUE THREAD

**Issue by ms-studio** [eracom/atlas#10]
Dans le modèle liste:

permettre de spécifier le paramètre de tri.

au lieu de lister alphabétiquement, permettre d'afficher par ordre alphabétique des Types.

**Comment by ms-studio** [comment]
Demande faite par @EmmanuelleWassnerEichmann pour le plan de formation MSCI

**Comment by ms-studio** [comment]
Observations: 

- l'ordre d'affichage dans le modèle Liste est défini avec `| sort: "title"` (par titre).
- dans le modèle Cursus, on ne spécifie pas le critère de tri (`assign cours = site.pages`) donc ils sont ordonnés par nom de fichier.

Dans un premier temps: on supprime le critère "title", ainsi ils vont être listés par nom de fichier partout.

Cf commit f7b8263f8203255442bc282f960e9b5cd332395e

**Comment by EmmanuelleWassnerEichmann** [comment]
Parfait.
Cela signifie que pour obtenir la même disposition correspondant au Plan de Formation,
j'applique le même modèle "chiffré" pour les titres de cours,
le chiffre étant déterminant pour respecter l'affichage des couleurs dans l'ordre souhaité ?
Merci.

**Comment by ms-studio** [comment]
Avec le dernier changement - 1bedabc5f76b395397843c49486e29b634c244c4 - on peut maintenant déterminer l'ordre, avec divers critères possibles:

- `title` (le réglage par défaut), 
- `path` (par nom du fichier, y compris le nom du dossier parent) 
- tout autre champ dans les métadonnées des cours: p.ex. `type`, `code`...

**Comment by EmmanuelleWassnerEichmann** [comment]
Encore deux questions :
1- Ne devrais-je pas être mentionnée comme "author" en ce qui concerne le Plan de Formation MSCI, ainsi que pour les Cours MSCI correspondants ; puisque je suis la seule personne à avoir concrètement effectué tout ce travail, entrepris depuis février 2018 ?
2- Comment je dois faire pour modifier le titre des cours, dans cours ?
J'ai pu le faire sans problème pour Plan d'Études puisque c'est moi qui en ai effectué la saisie, la semaine dernière… J'ai regardé si je pouvais accéder à un niveau qui me permettrait ces modifications, mais je n'ai pas trouvé ! Je pense que c'est parce que pour les cours c'est Viviane qui avait effectué la saisie initiale dans GitHub ?
Merci de bien vouloir me montrer comment faire ou de m'indiquer par téléphone la marche à suivre… À moins que nous y arrivions par message ?
…D'ailleurs, tu verras directement ce message ou bien faut-il que je te l'envoie aussi par Educanet2 ? Pour cette fois, dans le doute, je te l'envoie aussi par mail Educanet2.
